language: "en-US"
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  fail_commit_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  auto_approve:
    enabled: true
    conditions:
      - "files_changed <= 5"
      - "additions <= 100"
      - "deletions <= 50"
      - "!has_conflicts"
      - "!draft"

chat:
  auto_reply: true
